# Site

title: D8A
description: Data, Discovery & Decision Science
logo: /images/d8a.png
url: "http://d8a.org"
baseurl:

image: /images/d8a.png
intro: D8A is a social enterprise specializing in data, discovery & decision science.
  We promote practices and programs that benefit nature and society.

cta:
  about: Learn more about our areas of interest, mission and team members!
  projects: See what we are working on and get involved
  blog: Read our blog for updates on our projects
  home: Join our team of scientists, statisticians and storytellers!

social:
  - name: Facebook
    link: https://www.facebook.com/bioshack
    icon: facebook
  - name: GitHub
    link: https://github.com/bioshack
    icon: github-alt
  - name: LinkedIn
    link: https://www.linkedin.com/company/bioshack
    icon: linkedin
  - name: Twitter/X
    link: https://twitter.com/bioshack
    icon: twitter

summary: Social enterprise specializing in the data of everything (DoE)
email: https://letterbird.co/go
founded: 2016
github_repo: "https://github.com/bioshack/d8a"

# Build

paginate: 100
paginate_path: "/blog/:num/"

collections:
  - "people"
  - "projects"

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      background_image: /images/dots.png
      image: /images/d8a.png
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/:title/"
      layout: post
      _comments:
        image: Shown in social shares and the blog list.
  -
    scope:
      path: "blog"
    values:
      sitemap: false

permalink: pretty

jekyll-archives:
  enabled:
    - tags

gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
